# -*- coding: utf-8 -*-
"""task04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rqfTcl_bj_wqLuvUsnpL5ERoQaAz7aNW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Load the dataset
df = pd.read_csv("/content/drive/MyDrive/Elevate Labs/TASK04/Breast Cancer.csv")

df.head()

df.info()

df.isnull().sum()

df.columns

df["Unnamed: 32"].isnull().sum()

df = df.drop("Unnamed: 32", axis=1)

"""Convert Categorical Values"""

from sklearn.preprocessing import LabelEncoder

# Create an instance of LabelEncoder
label_encoder = LabelEncoder()

df = df.apply(label_encoder.fit_transform)

"""Split Training"""

from sklearn.model_selection import train_test_split

#Binary Classification Dataset

X = df.drop(["diagnosis", "id"], axis=1)
y = df["diagnosis"]

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""Logistic Regression"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, roc_auc_score
from sklearn.metrics import ConfusionMatrixDisplay

model = LogisticRegression()
model.fit(X_train, y_train)

#Make predictions
y_pred = model.predict(X_test)

#Evaluate model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)


print(f"Accuracy: {accuracy:.4f}")
print("Confusion Matrix: \n", conf_matrix)
print("Classification Report: \n", report)

#Confusion Matrix

ConfusionMatrixDisplay.from_predictions(y_test, y_pred)
plt.show()

"""Threshold and Sigmoid Function"""

from sklearn.metrics import roc_curve

fpr, tpr, thresholds = roc_curve(y_test, y_probs)

# Youden’s J statistic
j_scores = tpr - fpr
best_threshold = thresholds[np.argmax(j_scores)]

print("Best Threshold:", best_threshold)

# Apply best threshold
y_pred_best = (y_probs >= best_threshold).astype(int)

#Sigmoid Function

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Example
z = np.array([-3, -1, 0, 1, 3])
y = sigmoid(z)
print(sigmoid(z))

# Get predicted probabilities
y_probs = model.predict_proba(X_test)[:, 1]  # probability for class 1

# Default threshold = 0.5
y_pred_default = (y_probs >= 0.29).astype(int)

accuracy_thresh = accuracy_score(y_test, y_pred_default)

print(f"Accuracy with default threshold: {accuracy_thresh:.4f}")

#Confusion Matrix

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_default)
plt.show()

"""ROC-AUC Curve"""

fpr, tpr, thresholds = roc_curve(y_test, y_probs)
roc_auc = roc_auc_score(y_test, y_probs)

plt.figure(figsize=(6,6))
plt.plot(fpr, tpr, color='blue', label=f'ROC Curve (AUC = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='red', linestyle='--')  # Random classifier line
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

plt.figure()
plt.plot(z, y)
plt.title("Sigmoid Function")
plt.xlabel("z")
plt.ylabel("Sigmoid(z)")
plt.axhline(0.5)
plt.axvline(0)
plt.show()